replicaCount: 1

sharelatex:
  image: sharelatex/sharelatex
  appName: Overleaf Community Edition
  redisHost: redis
  mongoUrl: mongodb://mongo/sharelatex
  nodePort: 80
  storageSize: 5Gi
  mountPath: /var/lib/overleaf

mongo:
  image: mongo:6.0
  database: sharelatex
  storageSize: 5Gi
  mountPath: /data/db

redis:
  image: redis:6.2
  storageSize: 2Gi
  mountPath: /data

persistence:
  enabled: true
  storageClass: "longhorn"
  accessMode: ReadWriteOnce