replicaCount: 1

sharelatex:
  image: sharelatex/sharelatex
  appName: Overleaf Community Edition
  redisHost: redis
  mongoUrl: mongodb://mongo/sharelatex
  nodePort: 80
  volumeMount: /var/lib/overleaf
  dataPath: /home/user/sharelatex_data

mongo:
  image: mongo:6.0
  database: sharelatex
  volumeMount: /data/db
  dataPath: /home/user/mongo_data

redis:
  image: redis:6.2
  volumeMount: /data
  dataPath: /home/user/redis_data
