{{- if .Values.admin.create }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "overleaf-helm.fullname" . }}-create-admin
  labels:
    {{- include "overleaf-helm.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep
spec:
  template:
    spec:
      serviceAccountName: {{ include "overleaf-helm.fullname" . }}-admin
      restartPolicy: OnFailure
      containers:
        - name: create-admin
          image: {{ .Values.admin.job.image }}
          command:
            - sh
            - -c
            - |
              echo "Waiting for sharelatex pod to be Ready..."
              POD=""
              for i in $(seq 1 30); do
                POD=$(kubectl get pods -l app=sharelatex -o jsonpath='{.items[0].metadata.name}' 2>/dev/null)
                if [ -n "$POD" ]; then
                  STATUS=$(kubectl get pod "$POD" -o jsonpath='{.status.conditions[?(@.type=="Ready")].status}')
                  if [ "$STATUS" = "True" ]; then
                    echo "Pod $POD is Ready"
                    break
                  fi
                fi
                echo "Pod not ready yet, retrying..."
                sleep 2
              done

              if [ -z "$POD" ]; then
                echo "Error: could not find a ready sharelatex pod"
                exit 1
              fi

              echo "Running create-user.js in pod $POD..."
              kubectl exec "$POD" -- node /overleaf/services/web/modules/server-ce-scripts/scripts/create-user.js \
                --email "${OVERLEAF_ADMIN_USERNAME}" \
                --password "${OVERLEAF_ADMIN_PASSWORD}" || true
          env:
            {{- if .Values.admin.useSecret }}
            - name: OVERLEAF_ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.admin.secret.name }}
                  key: {{ .Values.admin.secret.usernameKey }}
            - name: OVERLEAF_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.admin.secret.name }}
                  key: {{ .Values.admin.secret.passwordKey }}
            {{- else }}
            - name: OVERLEAF_ADMIN_USERNAME
              value: {{ .Values.admin.username | quote }}
            - name: OVERLEAF_ADMIN_PASSWORD
              value: {{ .Values.admin.password | quote }}
            {{- end }}
{{- end }}
