apiVersion: apps/v1
kind: Deployment
metadata:
  name: sharelatex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sharelatex
  template:
    metadata:
      labels:
        app: sharelatex
    spec:
      enableServiceLinks: false

      # <-- Add initContainers here, before containers
      initContainers:
        - name: wait-for-mongo
          image: busybox
          command:
            - sh
            - -c
            - |
              until nc -z mongo 27017; do
                echo "Waiting for MongoDB..."
                sleep 2
              done

      containers:
        - name: sharelatex
          image: {{ .Values.sharelatex.image }}
          securityContext:
            runAsUser: 0
            runAsGroup: 0
            capabilities:
              add:
                - SYS_RESOURCE
          env:
            - name: OVERLEAF_APP_NAME
              value: {{ .Values.sharelatex.appName }}
            - name: OVERLEAF_REDIS_HOST
              value: {{ .Values.sharelatex.redisHost }}
            - name: REDIS_HOST
              value: {{ .Values.sharelatex.redisHost }}
            - name: OVERLEAF_MONGO_URL
              value: {{ .Values.sharelatex.mongoUrl }}
            # ... other env vars ...
          ports:
            - containerPort: 80
          volumeMounts:
            - name: sharelatex-data
              mountPath: {{ .Values.sharelatex.mountPath }}
      volumes:
        - name: sharelatex-data
          persistentVolumeClaim:
            claimName: sharelatex-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: sharelatex
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: sharelatex
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sharelatex-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.sharelatex.storageSize }}
  storageClassName: {{ .Values.persistence.storageClass }}