apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      hostAliases:
        - ip: "127.0.0.1"
          hostnames:
            - "mongo"
      containers:
        - name: mongo
          image: {{ .Values.mongo.image }}
          args: ["--replSet", "overleaf"]
          env:
            - name: MONGO_INITDB_DATABASE
              value: {{ .Values.mongo.database }}
          volumeMounts:
            - name: mongo-data
              mountPath: {{ .Values.mongo.mountPath }}
      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: mongo-pvc
        - name: mongo-init-script
          configMap:
            name: mongo-init-script
            defaultMode: 0755
